import { useState, type FormEvent, type ReactNode } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Eye, EyeOff, ArrowRight, AlertCircle } from 'lucide-react';
import { roles, type Role } from '../roles';
import '../workspace.css';
export function LoginPage(){
 const navigate=useNavigate();const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[show,setShow]=useState(false);const[error,setError]=useState('');
 function submit(e:FormEvent){e.preventDefault();const role=(Object.keys(roles) as Role[]).find(r=>roles[r].email===email.trim().toLowerCase());if(!role||password!=='equi123'){setError('The email or password is incorrect. Please try again.');return;}localStorage.setItem('equiflow:user',JSON.stringify({email:roles[role].email,fullName:roles[role].name,role}));navigate('/app');}
 return <AuthShell title="Welcome back." subtitle="Sign in to your club workspace." footer={<span>New to the club? <Link to="/register">Register with Gmail</Link></span>}>
 <form className="auth-form" onSubmit={submit}>{error&&<p role="alert" className="auth-alert"><AlertCircle size={18}/>{error}</p>}<label>Email address<input type="email" autoComplete="username" placeholder="you@gmail.com" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<div className="password-field"><input type={show?'text':'password'} autoComplete="current-password" placeholder="Enter your password" value={password} onChange={e=>setPassword(e.target.value)} required/><button type="button" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label><button type="submit">Sign in to workspace <ArrowRight size={18}/></button></form>
 <details className="demo-accounts"><summary>Explore the five demo accounts</summary><p>Choose an actor to fill the form. Password: <code>equi123</code></p>{(Object.keys(roles) as Role[]).map(r=><button key={r} onClick={()=>{setEmail(roles[r].email);setPassword('equi123');setError('')}}>{roles[r].name}<ArrowRight size={14}/></button>)}</details></AuthShell>;
}
export function AuthShell({title,subtitle,children,footer}:{title:string;subtitle:string;children:ReactNode;footer:ReactNode}){return <main className="auth-page refined-auth"><section className="auth-card"><Link className="auth-brand" to="/login"><img src="/images/logo-fivegates.svg" alt="EquiFlow"/> <span>EquiFlow<small>HORSE TRAINING & RACING CLUB</small></span></Link><div className="auth-inner"><p className="eyebrow">CLUB WORKSPACE</p><h1>{title}</h1><p className="auth-subtitle">{subtitle}</p>{children}<div className="auth-footer">{footer}</div></div><p className="auth-bottom">One workspace. Five roles. A shared standard of care.</p></section><section className="auth-art"><div><p className="eyebrow">EQUIFLOW / CONNECTED CARE</p><h2>One team.<br/>One shared goal.</h2><p>From the first morning feed to the finish line.<br/>Keep every part of your club in step.</p></div></section></main>;}

